# Configuration for the PR labeler
# https://github.com/actions/labeler

# Core integration files
integration:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/**'
      - '!custom_components/kiosker/README.md'

# Sensor platform
sensor:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/sensor.py'
      - 'custom_components/kiosker/binary_sensor.py'

# Configuration flow
config-flow:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/config_flow.py'
      - 'custom_components/kiosker/strings.json'

# Core coordinator and hub
coordinator:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/coordinator.py'
      - 'custom_components/kiosker/__init__.py'

# Events and buttons
events:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/events.py'
      - 'custom_components/kiosker/button.py'

# Constants and utilities
constants:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/const.py'
      - 'custom_components/kiosker/utils.py'

# Manifest and metadata
manifest:
  - changed-files:
    - any-glob-to-any-file:
      - 'custom_components/kiosker/manifest.json'
      - 'custom_components/kiosker/icons.json'

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '**/*.md'
      - 'README.md'
      - 'CHANGELOG.md'

# Tests
test:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - 'conftest.py'

# CI/CD
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - 'Makefile'
      - '.pre-commit-config.yaml'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'uv.lock'
      - 'requirements*.txt'

# HACS
hacs:
  - changed-files:
    - any-glob-to-any-file:
      - 'hacs.json'

# Configuration files
config:
  - changed-files:
    - any-glob-to-any-file:
      - '.editorconfig'
      - '.gitignore'
      - 'pyproject.toml'

# Build and development
build:
  - changed-files:
    - any-glob-to-any-file:
      - 'Makefile'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
